name: RSS to Discord

on:
  schedule:
    # 30分おきに自動実行
    - cron: '*/5 * * * *'
  workflow_dispatch: # 手動で「Run workflow」できるようにする設定

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          # 記事の本文を読み取るために beautifulsoup4 を追加しました
          pip install feedparser requests beautifulsoup4

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          WEBHOOK_YUTAI: ${{ secrets.WEBHOOK_YUTAI }}
          WEBHOOK_KESSAN: ${{ secrets.WEBHOOK_KESSAN }}
          RSS_URL: ${{ secrets.RSS_URL }}
          RSS_URL_2: ${{ secrets.RSS_URL_2 }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py

      - name: Commit and push state
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add state.json || true
          git commit -m "Update RSS state" || true
          git push
